require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5.1

Gemspec/RequiredRubyVersion:
  Enabled: false

Lint/HandleExceptions:
  Exclude:
    - bin/*

# Don't force top level comments in every class
Style/Documentation:
  Enabled: false

# Safe navigation is not available in older ruby versions
Style/SafeNavigation:
  Enabled: false

# A good line length is 100 chars
Metrics/LineLength:
  Max: 100
  AllowURI: true

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 300

Metrics/MethodLength:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/AbcSize:
  Max: 30

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10
